backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "listings"
    label: "İlanlar"
    folder: "content/listings"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "İlan Başlığı", name: "title", widget: "string" }
      - { label: "Fiyat", name: "price", widget: "string" }
      - { label: "Kategori", name: "category", widget: "select", options: ["Satılık", "Kiralık"], default: "Satılık" }
      - { label: "Konum (Şehir/İlçe)", name: "location", widget: "string", default: "Eskişehir" }
      - { label: "Google Maps Linki", name: "map_link", widget: "string", required: false }
      - label: "Fotoğraflar"
        name: "images"
        widget: "list"
        field: { label: "Görsel", name: "image", widget: "image" }
      - { label: "İlan Açıklaması", name: "description", widget: "text" }
